// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    // welcome
    'welcome': 'Bem vindo ao Gestor de Treinamento',

    // sidebar
    'sidebar.training': 'Training Plan',
    'sidebar.data': 'General Data',
    'sidebar.profile': 'Profile',
    'sidebar.logout': 'Logout',
    'sidebar.evaluation': 'Evaluation',
    'sidebar.pat': 'PAT',
    'sidebar.reaction': 'React Evaluation',
    'sidebar.efficiency': 'Efficiency Evaluation',
    'sidebar.dossier': 'Dossier',
    'sidebar.class': 'Classes',
    'sidebar.calendar': 'Calendar',
    'manager.performance': 'Performance Manager',
    'sidebar.my.dossier': 'My Dossier',
    'sidebar.public.calendar': 'Public Calendar',
    'sidebar.request': 'Request Training',
    'sidebar.subscription': 'Subscription',
    'sidebar.my.training': 'Courses',
    'sidebar.playlist': 'Playlist',
    'sidebar.diary': 'Diary',
    'sidebar.generate.knowledge': 'Generate Evaluation Knowledge',
    'sidebar.knowledge': 'Evaluation Knowledge',
    'sidebar.approves': 'Approvals',
    'sidebar.approves.training': 'Approvals',
    'sidebar.employee-external': 'Outsourced',

    'sidebar.ab.training': 'PT',
    'sidebar.ab.profile': 'P',
    'sidebar.ab.logout': 'S',
    'sidebar.ab.reaction': 'AR',
    'sidebar.ab.efficiency': 'AE',
    'sidebar.ab.my.dossier': 'MD',
    'sidebar.ab.public.calendar': 'CP',
    'sidebar.ab.request': 'ST',
    'sidebar.ab.subscription': 'IN',
    'sidebar.ab.my.training': 'CU',
    'sidebar.ab.knowledge': 'CO',
    'sidebar.ab.pat': 'PA',
    'sidebar.ab.approves.training': 'AP',


    // general
    'search': 'Search',
    'table.action': 'Quick Actions',
    'table.action2': 'Actions',
    'action.edit': 'Edit',
    'action.refresh': 'Update',
    'action.view': 'View Details',
    'action.export': 'Export List',
    'action.copy': 'Duplicate Registry',
    'action.approves': 'Evaluate Form',
    'action.delete': 'Disable Registry',
    'action.restore': 'Enable Registry',
    'action.send': 'Submit Form',
    'action.subscriptions': 'Subscription',
    'action.unsubscriptions': 'Cancel Subscription',
    'action.frequency': 'Perform Frequency',
    'action.list.frequency': 'Frequency Registration',
    'action.apprentice': 'List of Participants',
    'action.answer.evaluation': 'Answer Form',
    'action.certified': 'Certificate Listing',
    'action.approver': 'Evaluate',
    'action.download': 'Download',
    'action.view.movie': 'Watch class',
    'action.help': 'Ajuda',

    // buttons
    'button.save': 'Salvar',
    'button.back': 'Voltar',
    'button.update': 'Atualizar',
    'button.cancel': 'Cancelar',
    'button.next': 'Próximo',
    'button.submit': 'Submeter à Aprovação',
    'button.reject': 'Rejeitar',
    'button.approves': 'Aprovar',
    'button.add': 'Adicionar',
    'button.subscription': 'Confirm Registration',
    'button.add.new': 'Save & New',

    'view.title': 'Details',
    'view.info': 'Information',
    'loading': 'Updating ...',
    'all.register': 'All Records',
    'deleted.register': 'Disabled Records',
    'ative.register': 'Enabled Records',
    'reproved.register': 'Disapproved Records',
    'my.subscription': 'My Subscriptions',
    'more': 'More',

    // login
    'login': 'Login',
    'login.username': 'User',
    'login.password': 'Password',
    'login.recover.password': 'Recover Password',
    'login.request.password': 'Request Password',
    'recover.password': 'Recover Password',

    // Dossier
    'dossier.list.title': 'Dossier Listing',
    'dossier.update': 'Update Dossier',
    'dossier.table.employee': 'Employee',
    'dossier.table.role': 'Role',
    'dossier.table.status': 'Status',
    'dossier.table.training': 'Training',
    'dossier.table.ch': 'Workload',
    'dossier.table.progress': 'Progress',
    'dossier.add.training': 'Training',
    'dossier.treining.name': 'Training Name',
    'dossier.treining.expiration': 'Valid until',
    'dossier.treining.file.name': 'File Name',
    'dossier.treining.file.type': 'Format',
    'dossier.treining.file.size': 'Size',
    'dossier.treining.file.valid': 'Valid',
    'dossier.treining.file.no.valid': 'Null',
    'description.schooling': 'Schooling',

    // Training
    'training.list.title': 'List of Training Plans',
    'training.title': 'Training',
    'training.form.title': 'Register Training Plan',
    'training.form.title.edit': 'Edit Training',
    'training.create': 'Plan',
    'training.table.name': 'Training Plan',
    'training.table.ch': 'Workload',
    'training.table.status': 'Situation',
    'treining.form.name': 'Training Name',
    'treining.form.content': 'Training Content',
    'description.form.title': 'Training Details',
    'training.table.planned': 'Planned Training',
    'training.table.type': 'Training Type',
    'training.table.approved': 'Status',
    'training.table.requester': 'Requester',
    'training.table.area.requester': 'Sector Requisition',
    'training.table.provider': 'Provider',
    'training.table.justification': 'Training Justification',
    'training.table.resource': 'Didactic Resource',
    'training.table.value': 'Training Value',
    'training.planned.yes': 'Yes',
    'training.planned.no': 'No',
    'training.request': 'Request Training',
    'trainig.toManager': 'Need Approval from the Department Manager?',
    'training.approves.list.title': 'Training Approval List',
    'training.approves.justification': 'Justification',
    'training.approves.justificatio.hr': 'HR Justification',
    'training.approves.justification.manager': 'Manager justification',
    'msg.training.approves.form.justification': 'Justification is ',
    'info.KNOWLEDGE': `It involves the development of knowledge to improve performance, tailoring the employee's requirements as well as concepts information necessary to the understanding and the theoretical or practical mastery of subjects relevant to their duties. Know what and how it works. `,
    'info.ATTITUDE': `Acquire behavioral skills or need for development, such as: leadership, relationship, negotiation, communication, teamwork etc.`,
    'info.SKILL': `It consists of knowing how to do, applying knowledge, that is, putting theory into practice.`,
    'training.table.goal': 'Training Goal',
    'treining.evaluations': 'Evaluations to be Applied',
    'training.daysLater': 'Days After Training',
    'training.approves.hr': 'Human Resources Approval',
    'training.approves.manager': 'Manager Approval ',
    'training.without.approver': 'Waiting for Approval',
    'training.table.month': 'Month',
    'request.training.list.title': 'Training Request Listing',

    // Exam
    'exam.create': 'Evaluation',
    'exam.list.title': 'Evaluation List',
    'exam.table.type': 'Evaluation Type',
    'exam.table.date': 'Evaluation Date',
    'exam.form.description': 'Evaluation Description',
    'training.add.exam': 'Add Evaluation',

    // turmas
    'class.list.title': 'Class List',
    'class.create': 'Class',
    'class.form.title': 'Class Registration',
    'class.form.title.edit': 'Edit Class',
    'class.form.step1': 'Class Settings',
    'class.form.step2': 'Class Students',
    'class.form.treining': 'Training',
    'class.form.classroom': 'Place',
    'class.form.time': 'Start Time',
    'class.form.professor': 'Instructor',
    'class.form.type.professor': 'Instructor Type',
    'class.form.begin': 'Start date',
    'class.form.end': 'End Date',
    'class.form.limit': 'Limit of Students',
    'class.form.subscription': 'Public Subscription',
    'class.apprentices.internal': 'Internal Student',
    'class.apprentices': 'Student Name',
    'class.apprentices.register': 'Student Registration',
    'add.apprentices': 'Add Student',
    'class.form.pat.year': 'PAT Year',
    'class.form.duration': 'Closing time',
    'class.form.responsible': 'Responsável pela Turma',
    'class.form.pat.week': 'Days of the week',
    'class.form.step3': 'Attach Class Evidence',
    'apprentices.list.title': 'Student List',
    'apprentice.table.justification': 'Registration Justification',

    // registered
    'registered.list.title': 'Students List',
    'registered.create': 'Student',
    'registered.form.employee': 'Employee',

    // subscription
    'subscription.inf': 'I declare that I undertake to participate fully in the course.',
    'subscription.declaro.inf': 'I declare that I am not able to participate fully in the course.',

    // react Evaluation
    'react.form.title': 'Reaction evaluation',
    'react.inf': `Seeking continuous improvement in our training process, we would like to hear your opinion about some aspects of the event you attended.`,
    'react.inf2': `Check only one alternative for each question. For questions 1 through 10, use:`,
    'react.question.1': '1. Has the program met your expectations ?',
    'react.question.2': '2. Have you acquired new knowledge ?',
    'react.question.3': '3. Did the teaching material make possible the understanding of the content ?',
    'react.question.4': '4. Was the workload compatible with the content ?',
    'react.question.5': '5. Were the facilities adequate? (Place, resources and infrastructure)',
    'react.question.6': '6. I had an interested and participative posture during the program ?',
    'react.question.7': '7. Has the facilitator mastered the subject and been able to convey it satisfactorily ?',
    'react.question.8': '8. Was the facilitator always willing to clarify the doubts that have arisen ?',
    'react.question.9': '9. Will this training enable you to do a more efficient job ?',
    'react.question.10': '10. General evaluation of the course.',
    'react.alternative.1': '1 - Bad',
    'react.alternative.2': '2 - Regular',
    'react.alternative.3': '3 - Good',
    'react.alternative.4': '4 - Great',
    'react.view.form': 'View Form',
    'react.list.title': 'Evaluation React List',
    'react.btn.responder': 'Answered Evaluations',
    'react.btn.semresponder': 'Evaluation to Answer',
    'react.comment.weak': 'Points to Improve',
    'react.comment.strong': 'Strengths of Training',
    'react.comment.comments': 'comments',

    'efficiency.list.title': 'Evaluation Efficiency List',

    // pat
    'list.pat': 'PAT List',
    'manager.pat': 'Annual Training Plan',
    'create.pat': 'Adding Annual Training Plan',
    'edit.pat': 'Editing Annual Training Plan',
    'manger.pat.view': 'Training Schedule',
    'new.pat': 'PAT',
    'pat.form.send': 'Issued by',
    'pat.form.approved': 'Validated',
    'pat.form.obs': 'Comments',
    'pat.form.send.date': 'Approval date',
    'pat.add.training': 'Add Training',
    'pat.approvedBy': 'Validator',
    'pat.form.observations': 'Comments',
    'pat.form.status': 'Status',
    'pat.statistics': 'Statistics',
    'pat.form.training.month': 'Training Month',
    'pat.form.training.done': 'Training Completed',

    'employee.company': 'Company',
    'employee.form': 'Outsourced Registration',
    'employee.form.edit': 'Edit Outsourced Registration',
    'employee.form.username': 'Access Name',
    'employee.form.password': 'Password',
    'employee.form.passwordconfirm': 'Confirm the Password',
    'external.list.title': 'Outsourcer List',
    'external.create': 'Outsourced',


    // diary
    'diary.form.title': 'Attendance list',
    'diary.form.date': 'Class day',
    'diary.form.training': 'Training',
    'diary.form.present': 'Was present',
    'class.apprentice': 'Participants',
    'class.present': 'Presence',
    'diary.no.apprentices': 'Presence not performed on this day',

    // efficiency
    'efficiency.form.title': 'Efficiency Evaluation',
    'efficiency.question.1': '1- KNOWLEDGE: TRAINING INCREASED LEVEL OF KNOWLEDGE TO THE EMPLOYEE ?',
    'efficiency.question.2': `2- SKILLS: WHAT IS THE EMPLOYEE LEARNED IS BEING PLACED IN PRACTICE IN THE ACTIVITIES WITHIN THE ORGANIZATION ?`,
    'efficiency.question.3': '3- ATTITUDES: DO YOU REALIZE NEW POSITIVE ATTITUDES OF THE EMPLOYEE AFTER THE TRAINING ?',
    'efficiency.form.porcent': 'Percentage (%): ',
    'efficiency.form.description': 'Comments: ',
    'efficiency.question.comment1': 'Final Report of the Leader (Previous Situation x Current Situation)',
    'efficiency.question.comment2': 'Exemplify improvements observed after the training performed by the employee.',

    // enum
    'KNOWLEDGE': 'Knowledge',
    'ATTITUDE': 'Attitude',
    'SKILL': 'Abiliity',
    'RESPONSE': 'Reaction',
    'EFFICIENCY': 'Efficiency',
    'UPDATE': 'Update',
    'FORMATION': 'Formation',

    // msg error
    'msg.dossier.treining.name': 'Training Name is',
    'msg.dossier.treining.size': 'Training Name must contain at least 3 characters',
    'msg.dossier.ch': 'Training Workload is',
    'msg.treining.requester': 'Requester is',
    'msg.treining.provider': 'Supplier is',
    'msg.treining.value': 'Training Value is',
    'msg.treining.resource': 'Didactic Resource is',
    'msg.treining.criterion.provider': 'The Supplier choice is',
    'msg.treining.area.requester': 'Requester is',
    'nofile': 'No file selected',
    'files.selected': 'Selected File (s)',
    'msg.treining.ch': 'Working Hours are',
    'msg.class.form.classroom': 'Place is',
    'msg.class.form.limit': 'Numbers of Students is',
    'msg.class.form.time': 'Shift is',
    'msg.class.form.begin': 'Initial Date is',
    'msg.class.form.end': 'Final date is',
    'msg.class.form.professor': 'Instructor is',
    'msg.employee.registration': 'Registration is',
    'msg.login.username': 'User is',
    'msg.login.password': 'Password is',
    'msg.login.size': 'Username must contain at least 3 characters.',
    'msg.unsubscription.sucess': 'Registration Canceled Successfully',
    'msg.pat.approvedBy': 'Validator is',
    'msg.diary.form.date': 'Class day is',
    'msg.exam.type': 'Evaluation Type is',
    'msg.treining.goal': 'Training Goal is',
    'msg.treining.type': 'Training Type is',
    'msg.exam.form.date': 'Evaluation Date is',
    'msg.class.form.responsible': 'Responsible for the class is',
    'msg.username.name': 'Access Name is',
    'msg.username.size': 'The Access Name must contain between 5 and 100 characters.',
    'msg.password.name': 'Password is',
    'msg.password.size': 'Password must contain between 6 and 100 characters.',
    'msg.password.error': 'Passwords do not match.',
    'msg.employee.name': 'Employee Name is',
    'msg.employee.size': 'Employee Name must contain between 5 and 100 characters.',
    'msg.employee.not.found': 'No Employee found',
    'msg.register.name': 'Registration is',
    'msg.register.size': 'Registration must contain a maximum of 11 characters.',
    'msg.employee.company': 'Company Name is',
    'msg.employee.company.size': 'Company name must contain between 3 and 100 characters.',

    'employee.name': 'Employee ',
    'employee.registration': 'Registration',
    'employee.status': 'Situation',
    'department': 'Department',
    'role': 'Role',
    'data.employee': 'Employee Data',
    'skill.list': 'Required Skills List',
    'skill.list.complete': 'Training Courses List',
    'tab.skill.technicalDesirable': 'Desirable Skills',
    'tab.skill.technicalIndispensable': 'Indispensável Skills',
    'tab.skill.performace': 'Performance Competencies',
    // ALERT
    'alert.success.titleRequest': 'Success !',
    'alert.success.text': 'The form was successfully submitted.',

    'alert.cancel.titleRequest': 'Ops !',
    'alert.cancel.text': 'We had a problem performing this operation.',

    'alert.warning.titleRequest': 'Attention  !',
    'alert.warning.text': 'The form was successfully submitted.',

    'alert.confirm.cancel.titleRequest': 'Attention !',
    'alert.confirm.cancel.text': 'Do you really want to do this? Canceling your changes will be lost.',
    'alert.confirm.cancel.buttonConfirm': 'Yes',
    'alert.confirm.cancel.buttonCancel': 'No',

    'alert.confirm.delete.titleRequest': 'Attention !',
    'alert.confirm.delete.text': 'Do you really want to delete this record? Confirming it can\'t be restored.',
    'alert.confirm.delete.buttonConfirm': 'Yes',
    'alert.confirm.delete.buttonCancel': 'No',

    'alert.confirm.edit.titleRequest': 'Attention !',
    'alert.confirm.edit.text': 'Do you really want to do this ?',
    'alert.confirm.edit.buttonConfirm': 'Yes',
    'alert.confirm.edit.buttonCancel': 'No',

    'alert.confirm.save.titleRequest': 'Attention !',
    'alert.confirm.save.text': 'Do you really want to do this? Canceling your changes will be lost.',
    'alert.confirm.save.buttonConfirm': 'Yes',
    'alert.confirm.save.buttonCancel': 'No',

    // toast
    'messageText.save': 'Record Saved Successfully',
    'messageText.edit': 'Record Updated Successfully',
    'messageText.delete': 'Record Disabled Successfully',
    'messageText.error': 'Ops, there was an unexpected error',
    'export.success': 'Exported Spreadsheet successfully',
    'import.success': 'Spreadsheet Imported Successfully',
    'export.error': 'Error Exporting spreadsheet',
    'import.error': 'Error Importing spreadsheet',
    'notenet': 'We are having trouble accessing the internet :(',
    'authorization': 'Your session has expired, you will be redirected to Login screen.',
    'attention': 'Attention',
    'information': 'Information',
    'instructions': 'Instructions',
    'notserve': 'Server is temporarily unavailable, please try again later. :/',

    // Approves
    'APROVED': 'Approved',
    'DISAPPROVED': 'Return to Correction',
    'WAITING': 'Waiting for approval',
    'APPROVED': 'Approved',
    'REJECTED': 'Return to Correction',

    // validation form
    'required': 'Required',
    'msg.error.length': 'No data registered',

    // actions
    'visualizar': 'View',
    'cadastrar': 'Register',
    'atualizar': 'Update',
    'desativar': 'Disable',

    // code msg back
    'username.not.found': 'Invalid User or Password',
    'user.password.mismatch': 'Invalid User or Password',
    'password.short': 'Invalid User or Password',
    'database.violation': 'Problem processing information',
    'permission.violation': 'You do not have permission to perform this action.',
    'user.name.violation': 'Access name is already in use',
    'idx.atp.year.violation': 'The Year chosen is already in use.',

    // recovery
    'register.indirect': 'Check your email to proceed with password recovery.',
    'register.update': 'Password Updated Successfully.',
    'register.direct': 'Please go to HR to change your password.',
    'register.notfound': 'User Registration not found on the system',

    // Dossier
    'dossier.msg.role.description': 'Job description',
    'dossier.msg.role.description.1': 'The Role of the Employee has no',
    'dossier.msg.role.description.2': 'registered.',
    'dossier.msg.files': 'Attach file (s)',
    'dossier.table.file': 'File',
    'evidence.interno': 'Internal',
    'evidence.externo': 'External',
    'evidence.institute': 'Acting Institution',
    'evidence.facilitator': 'Training Facilitator',

    'lang': 'Language',
    'Português': 'Portuguese',
    'English': 'English',
    'Chinês': 'Chinese',

    // Courses
    'courses.all': 'All Courses',
    'courses.my': 'Subscribed Courses',
    'courses.list': 'File List',
    'courses.description': 'Description',

    // Playlist
    'playlist.list.title': 'Playlist',
    'playlist.form.title': 'Add Playlist',
    'playlist.form.title.edit': 'Edit Playlist',
    'playlist.create': 'Playlist',
    'playlist.form.name': 'Name',
    'playlist.form.description': 'Description',
    'playlist.form.files.lenght': 'Number of files',
    'msg.playlist.form.name': 'The playlist name is',
    'msg.playlist.form.description': 'Description is',
    'playlist.file.wallpaper': 'Select Cover',
    'playlist.add.file': 'Add Files',
    'playlist.upload.file': 'Upload',
    'playlist.file.name': 'File Name',
    'playlist.file.progress': 'Upload Progress',
    'playlist.movies': 'Select Files to Upload',
    'playlist.select.wallpaper': 'Select Cover',
    'playlist.files': 'File List',
    'playlist.file.orden': 'Order',
    'playlist.file.type': 'Type',
    'playlist.file.extension': 'Extension',
    'playlist.file.actions': 'Actions',
    'playlist.form.step1': 'Playlist settings',
    'playlist.form.step2': 'Upload Content',

    // outher
    'money': '$',

    // Calendar
    'calendar.modal.msg': 'Do you want to register for this training?',
    'calendar.modal.start.date': 'Begins day ',
    'calendar.modal.end.date': 'End day ',

    'list.form.knowledge': 'Knowledge Evaluation List',

    // genearete
    'generate.title': 'Knowledge Evaluation Generator',
    'generate.description': 'Evaluation Description',
    'create.form': 'Create Evaluation',
    'OPEN': 'Simple Reply',
    'MULTIPLE_CHOICE': 'Multiple choice',
    'SELECTION_BOX': 'Selection box',
    'DATE': 'Date',
    'form.generate.title': 'Evaluation Title',
    'form.generate.date': 'Date of realization',

    //
    'question': 'Question',
    'Option': 'Option',
    'weight': 'Weight',
    'generate.correct': 'Right assertive',
    'yes': 'Yes',
    'no': 'No',
    'btn.add': 'Add',
    'hours': 'Hours',


    'data.general': 'General data',
    'number.employee': 'Number of Employees with Position',
    'number.roledescription': 'Number of Approved Job Description',
    'update.as': 'Last update ',
    'data.competency': 'Training Demand',

    'button.add.signature': 'Add Signature',
    'info.2.1': 'Click on the file pick button',
    'file.selected': 'Selected File',

    'mask.prefix.money': '$ ',
    'mask.money': '99999.00',
    'mask.sufix.hours': ' H',

    'employee.form.manage': 'Profile',
    'msg.authorities.name': 'Profile is',
    'msg.authorities.size': 'Profile must contain between 3 and 100 characters.',
    'list.appraiser': 'Approval Status',
    'recovery': 'Registration Enabled Successfully',

    // DashBoard
    'data.trainig': 'T&D - Statistical Analysis of Training',
    'title.hours.training': 'T&D - TRAINING HOURS',
    'title.planned.training': 'T&D - PLANNED X ACHIEVED',
    'description.hours.training': 'Monthly training load per month.',
    'training.serie.a': 'Planned Training',
    'training.serie.b': 'Unplanned Trainings',
    'training.serie.c': 'Conducted trainings',

    'data.eficiency': 'T&D - Training Effectiveness',
    'param.eficacia': 'Effectiveness Parameter',
    'title.eficacia.training': 'Effectiveness of Trainings Made (%)',
    'title.eficacia.median': 'Average Effectiveness Rating',
    'title.eficacia.realizado': 'Trainings Done X Effective Trainings',
    'eficacia.serie.a': 'Training Done',
    'eficacia.serie.b': 'Effective Training',
    'title.media.react': 'Average of the Reaction Evaluation of the Training Performed',
    'title.qtd.react': 'Number of Evaluated Training per Month',
    'data.react': 'T&D - Training Reaction',
    'title.qtd.largeness': 'T&D - Training Scope',
    'data.largeness': 'T&D - Scope',
    'descriptions.qtd.largeness': 'Number of Employees who completed Training per Month.',

    'JANUARY': 'Jan',
    'FEBRUARY': 'Feb',
    'MARCH': 'Mar',
    'APRIL': 'Apr',
    'MAY': 'May',
    'JUNE': 'Jun',
    'JULY': 'Jul',
    'AUGUST': 'Aug',
    'SEPTEMBER': 'Sep',
    'OCTOBER': 'Oct',
    'NOVEMBER': 'Nov',
    'DECEMBER': 'Dec',

    'update.there': 'Updated there ago',
    'update.now': 'Updated now',
    'update.min': 'minto',
    'update.mins': 'mintos',
    'update.hour': 'hour',
    'update.hours': 'hours',
    'update.atras': 'behind',
    'total.hours.training': 'Total Hours of Training During the Year:',
    'not.data.dash': 'No data to display',

    'title.diary.training': 'T&D - Presences X Absences',
    'diary.serie.a': 'Presence',
    'diary.serie.b': 'Absence',
    'data.register.warning': 'Some selected records are already registered',
    'not.response': 'Evaluation not answered',
    'total.planned.training': 'Total Trainings planned for the year ',
    'total.react.training': 'Total Reaction Evaluation Accomplished in  ',
    'total.apprentice.training': 'Total number of employees trained in  ',
    'median.planned.training': 'Total training effectiveness average of the year ',
    'total.eficacia.training': 'Total Effective Training in the Year of ',
    'median.react.training': 'Annual mean of the reaction',
    'total.diary.presence': 'Total Presence registered in the year of ',
    'total.diary.lack': 'Total Absences recorded in the year of '
};
